name: Changelog

on:
  push:
    branches:
      - main
    paths-ignore:
      - CHANGELOG.md
  workflow_dispatch:

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        id: git-cliff
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Commit changelog
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 'chore(changelog): update changelog'
          file_pattern: CHANGELOG.md
          disable_globbing: true
